services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:8080

      # Database config
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=appdb;Username=admin;Password=admin123;Include Error Detail=true

      # Frontend Configuration
      - Frontend__BaseUrl=http://localhost

    depends_on:
      - postgres

  client:
    image: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5001:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - client

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mount the database initialization scripts
      - ./database/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

volumes:
  pgdata:
